// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BigInt> addOne({required BigInt left, required BigInt right}) =>
    RustLib.instance.api.crateApiApi2AddOne(left: left, right: right);

Future<BigInt> addThree({required BigInt left, required BigInt right}) =>
    RustLib.instance.api.crateApiApi2AddThree(left: left, right: right);

String greet({required String name}) =>
    RustLib.instance.api.crateApiApi2Greet(name: name);

String helloworld() => RustLib.instance.api.crateApiApi2Helloworld();
