// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../bdk/error.dart';
import '../bdk/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RustAccount {
  const RustAccount();

  Future<Balance> getBalance({dynamic hint}) =>
      RustLib.instance.api.rustAccountGetBalance(
        that: this,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAccount && runtimeType == other.runtimeType;
}
