// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../proton_api/errors.dart';
import '../proton_api/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<AuthInfo> fetchAuthInfo({required String userName, dynamic hint}) =>
    RustLib.instance.api.fetchAuthInfo(userName: userName, hint: hint);

Future<void> initApiService({dynamic hint}) =>
    RustLib.instance.api.initApiService(hint: hint);
