// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../proton_api/contacts.dart';
import '../proton_api/errors.dart';
import '../proton_api/event_routes.dart';
import '../proton_api/exchange_rate.dart';
import '../proton_api/user_settings.dart';
import '../proton_api/wallet.dart';
import '../proton_api/wallet_account.dart';
import '../proton_api/wallet_settings.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `PROTON_API` is not used by any `pub` functions, thus it is ignored.

Future<void> initApiService(
        {required String userName, required String password, dynamic hint}) =>
    RustLib.instance.api
        .initApiService(userName: userName, password: password, hint: hint);

Future<List<WalletData>> getWallets({dynamic hint}) =>
    RustLib.instance.api.getWallets(hint: hint);

Future<WalletData> createWallet(
        {required CreateWalletReq walletReq, dynamic hint}) =>
    RustLib.instance.api.createWallet(walletReq: walletReq, hint: hint);

Future<ProtonWallet> updateWalletName(
        {required String walletId, required String newName, dynamic hint}) =>
    RustLib.instance.api
        .updateWalletName(walletId: walletId, newName: newName, hint: hint);

Future<void> deleteWallet({required String walletId, dynamic hint}) =>
    RustLib.instance.api.deleteWallet(walletId: walletId, hint: hint);

Future<List<WalletAccount>> getWalletAccounts(
        {required String walletId, dynamic hint}) =>
    RustLib.instance.api.getWalletAccounts(walletId: walletId, hint: hint);

Future<WalletAccount> createWalletAccount(
        {required String walletId,
        required CreateWalletAccountReq req,
        dynamic hint}) =>
    RustLib.instance.api
        .createWalletAccount(walletId: walletId, req: req, hint: hint);

Future<WalletAccount> updateWalletAccountLabel(
        {required String walletId,
        required String walletAccountId,
        required String newLabel,
        dynamic hint}) =>
    RustLib.instance.api.updateWalletAccountLabel(
        walletId: walletId,
        walletAccountId: walletAccountId,
        newLabel: newLabel,
        hint: hint);

Future<void> deleteWalletAccount(
        {required String walletId,
        required String walletAccountId,
        dynamic hint}) =>
    RustLib.instance.api.deleteWalletAccount(
        walletId: walletId, walletAccountId: walletAccountId, hint: hint);

Future<ApiUserSettings> getUserSettings({dynamic hint}) =>
    RustLib.instance.api.getUserSettings(hint: hint);

Future<ApiUserSettings> bitcoinUnit(
        {required CommonBitcoinUnit symbol, dynamic hint}) =>
    RustLib.instance.api.bitcoinUnit(symbol: symbol, hint: hint);

Future<ApiUserSettings> fiatCurrency(
        {required ApiFiatCurrency symbol, dynamic hint}) =>
    RustLib.instance.api.fiatCurrency(symbol: symbol, hint: hint);

Future<ApiUserSettings> twoFaThreshold({required int amount, dynamic hint}) =>
    RustLib.instance.api.twoFaThreshold(amount: amount, hint: hint);

Future<ApiUserSettings> hideEmptyUsedAddresses(
        {required bool hideEmptyUsedAddresses, dynamic hint}) =>
    RustLib.instance.api.hideEmptyUsedAddresses(
        hideEmptyUsedAddresses: hideEmptyUsedAddresses, hint: hint);

Future<ProtonExchangeRate> getExchangeRate(
        {required CommonBitcoinUnit bitcoinUnit,
        required ApiFiatCurrency fiatCurrency,
        int? time,
        dynamic hint}) =>
    RustLib.instance.api.getExchangeRate(
        bitcoinUnit: bitcoinUnit,
        fiatCurrency: fiatCurrency,
        time: time,
        hint: hint);

Future<String> getLatestEventId({dynamic hint}) =>
    RustLib.instance.api.getLatestEventId(hint: hint);

Future<List<ProtonEvent>> collectEvents(
        {required String latestEventId, dynamic hint}) =>
    RustLib.instance.api
        .collectEvents(latestEventId: latestEventId, hint: hint);

Future<List<ProtonContactEmails>> getContacts({dynamic hint}) =>
    RustLib.instance.api.getContacts(hint: hint);
