// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MyTestObject {
  const MyTestObject();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MyTestObject> newInstance({dynamic hint}) =>
      RustLib.instance.api.myTestObjectNew(hint: hint);

  Future<String> readText({dynamic hint}) =>
      RustLib.instance.api.myTestObjectReadText(that: this, hint: hint);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MyTestObject && runtimeType == other.runtimeType;
}
