// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SRPProofB64 {
  final String clientEphemeral;
  final String clientProof;
  final String expectedServerProof;

  const SRPProofB64({
    required this.clientEphemeral,
    required this.clientProof,
    required this.expectedServerProof,
  });

  @override
  int get hashCode =>
      clientEphemeral.hashCode ^
      clientProof.hashCode ^
      expectedServerProof.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SRPProofB64 &&
          runtimeType == other.runtimeType &&
          clientEphemeral == other.clientEphemeral &&
          clientProof == other.clientProof &&
          expectedServerProof == other.expectedServerProof;
}
