name: wallet
description: "Proton Wallet for Bitcoin"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+70

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  ffi: ^2.1.2

  ####rust
  rust_builder:
    path: rust_builder
  # frb
  flutter_rust_bridge: 2.1.0

  #golang ffi plugin
  proton_crypto:
    path: gopenpgp_plugin

  freezed_annotation: ^2.4.4
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  animated_size_and_fade: ^4.0.0
  flutter_tags_x: ^1.1.0
  flutter_screen_lock: ^9.0.1
  sqflite: ^2.3.3+1
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  # easy_sidemenu: ^0.5.0 # might use later
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  flutter_local_notifications: ^17.2.2
  sqflite_common_ffi: ^2.3.1
  web_socket_channel: ^3.0.1 # might use later
  introduction_screen: ^3.1.12
  confetti: ^0.7.0
  local_auth: ^2.1.7
  fluttertoast: ^8.2.4
  path_provider: ^2.1.1
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  fl_chart: ^0.66.0
  crypto: ^3.0.3
  url_launcher: ^6.2.2
  #Simple, fast generation of RFC4122 UUIDs.
  uuid: ^4.2.2
  #Contains utility functions and classes in the style of dart:collection to make working with collections easier.
  collection: ^1.18.0
  http: ^1.1.2
  flutter_secure_storage: ^9.0.0
  flutter_easyloading: ^3.0.5
  connectivity_plus: ^6.0.1
  toggle_switch: ^2.3.0
  xml: ^6.5.0
  # https://docs.ramp.network/mobile/flutter-sdk
  # issues: https://developers.google.com/ml-kit/known-issues#ios_issues
  ramp_flutter: ^3.0.0
  # json serializable depends on this
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3 # better use with flutter bloc
  animated_flip_counter: ^0.3.4
  sqlite3_flutter_libs: ^0.5.24
  chips_choice: ^3.0.1
  just_the_tooltip: ^0.0.12
  country_flags: ^3.0.0

  ### database
  drift: ^2.19.1

  # hive, shared_perferences is not stable
  hive: ^2.2.3
  hive_flutter: any
  currency_text_input_formatter: ^2.2.3
  #
  synchronized: ^3.1.0+1
  dart_style: ^2.3.6
  envied: ^0.5.4+1
  webview_flutter: ^4.8.0
  #
  country_picker: ^2.0.26
  currency_picker: ^2.0.21
  card_loading: ^0.3.2

  # this is for app version and user agent
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

  # keyboard visibility check. for toolbar on top of ios device
  flutter_keyboard_visibility: ^6.0.0

  # unleash proxy client
  unleash_proxy_client_flutter: ^1.5.3
  # sentry_flutter: ^8.3.0
  sentry: ^8.3.0
  permission_handler: ^11.3.1
  # workaround for java complier error. ref repo only changed gradle file
  qr_code_scanner:
    git:
      url: https://github.com/dola99/qr_code_scanner
      ref: update

# dependency_overrides:
#   # needs to override dependency for flutter_localizations (it depends on ^0.18.1, while flutter@3.22.0 depends on ^0.19.0)
#   intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  intl_translation: ^0.20.0
  ffigen: ^13.0.0
  build_runner: ^2.4.12
  analyzer: ^6.7.0
  #auto gen assets to const
  flutter_gen_runner: ^5.6.0
  freezed: ^2.5.7
  test: ^1.25.7
  flutter_gen: ^5.6.0

  # auto config app icons
  flutter_launcher_icons: ^0.13.1
  # json serializable
  json_serializable: ^6.8.0

  ## dev tools
  # meta: ^1.14.0
  drift_dev: ^2.19.1
  envied_generator: ^0.5.4+1

  # for ui tests
  golden_toolkit: ^0.15.0
  mockito: ^5.4.4

#flutter launcher icons configs
flutter_launcher_icons:
  image_path: "assets/images/icon/launch_icon.png"
  android: false
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  # background_color_ios: "#ffffff"
  web:
    generate: false
  windows:
    generate: true
    # image_path: "assets/images/icon-1024x1024.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    # image_path: "assets/images/icon-1024x1024.png"

# flutter_gen configs
flutter_gen:
  output: lib/constants/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true
  colors:
    inputs:
      - assets/colors/colors.xml

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icon/
    - assets/images/logos/
    - assets/images/wallet_creation/
    - assets/images/welcome/
    - assets/json/

  fonts:
    # we are using InterDisplay font
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf

        # - asset: assets/fonts/Inter-Bold.ttf
        # - asset: assets/fonts/Inter-Italic.ttf
        # - asset: assets/fonts/Inter-Light.ttf
        # - asset: assets/fonts/Inter-Medium.ttf
        # - asset: assets/fonts/Inter-Regular.ttf
        # - asset: assets/fonts/Inter-SemiBold.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
