// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../../proton_api/proton_users.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbUserKeyStore>>
abstract class FrbUserKeyStore implements RustOpaqueInterface {
  Future<void> clearAuthDartCallback();

  factory FrbUserKeyStore() => RustLib.instance.api
      .crateApiProtonWalletStorageUserKeyStoreFrbUserKeyStoreNew();

  Future<void> setGetDefaultUserKeyCallback(
      {required FutureOr<ProtonUserKey> Function(String) callback});

  Future<void> setGetPassphraseCallback(
      {required FutureOr<String> Function(String) callback});
}
