// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../../proton_api/wallet.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbWalletKeyStore>>
abstract class FrbWalletKeyStore implements RustOpaqueInterface {
  Future<void> clearAuthDartCallback();

  factory FrbWalletKeyStore() => RustLib.instance.api
      .crateApiProtonWalletStorageWalletKeyStoreFrbWalletKeyStoreNew();

  Future<void> setGetWalletKeysCallback(
      {required FutureOr<List<ApiWalletKey>> Function() callback});

  Future<void> setSaveWalletKeysCallback(
      {required FutureOr<void> Function(List<ApiWalletKey>) callback});
}
