// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../../proton_wallet/storage/wallet_mnemonic_ext.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbWalletMnemonicStore>>
abstract class FrbWalletMnemonicStore implements RustOpaqueInterface {
  Future<void> clearAuthDartCallback();

  factory FrbWalletMnemonicStore() => RustLib.instance.api
      .crateApiProtonWalletStorageWalletMnemonicStoreFrbWalletMnemonicStoreNew();

  Future<void> setGetWalletKeysCallback(
      {required FutureOr<List<MnemonicData>> Function() callback});

  Future<void> setSaveWalletKeysCallback(
      {required FutureOr<void> Function(List<MnemonicData>) callback});
}
