// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../proton_api/contacts.dart';
import '../../proton_api/event_routes.dart';
import '../../proton_api/exchange_rate.dart';
import '../../proton_api/proton_users.dart';
import '../../proton_api/user_settings.dart';
import '../../proton_api/wallet.dart';
import '../../proton_api/wallet_account.dart';
import '../../proton_api/wallet_settings.dart';
import '../errors.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'proton_api_service.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EventClient>>
abstract class EventClient implements RustOpaqueInterface {
  Future<List<ProtonEvent>> collectEvents({required String latestEventId});

  Future<String> getLatestEventId();

  Future<bool> isValidToken();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<EventClient> newInstance({required ProtonApiService service}) =>
      RustLib.instance.api
          .crateApiApiServiceEventClientEventClientNew(service: service);
}
