// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../proton_api/errors.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'proton_api_service.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InviteClient>>
@sealed
class InviteClient extends RustOpaque {
  InviteClient.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  InviteClient.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_InviteClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_InviteClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_InviteClientPtr,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<InviteClient> newInstance(
          {required ProtonApiService service, dynamic hint}) =>
      RustLib.instance.api.inviteClientNew(service: service, hint: hint);

  Future<int> sendEmailIntegrationInvite(
          {required String inviteeEmail, dynamic hint}) =>
      RustLib.instance.api.inviteClientSendEmailIntegrationInvite(
          that: this, inviteeEmail: inviteeEmail, hint: hint);

  Future<int> sendNewcomerInvite(
          {required String inviteeEmail, dynamic hint}) =>
      RustLib.instance.api.inviteClientSendNewcomerInvite(
          that: this, inviteeEmail: inviteeEmail, hint: hint);
}
