// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../common/errors.dart';
import '../../frb_generated.dart';
import '../../proton_api/proton_address.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'proton_api_service.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProtonEmailAddressClient>>
@sealed
class ProtonEmailAddressClient extends RustOpaque {
  ProtonEmailAddressClient.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  ProtonEmailAddressClient.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_ProtonEmailAddressClient,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_ProtonEmailAddressClient,
    rustArcDecrementStrongCountPtr: RustLib.instance.api
        .rust_arc_decrement_strong_count_ProtonEmailAddressClientPtr,
  );

  Future<List<AllKeyAddressKey>> getAllPublicKeys(
          {required String email, required int internalOnly, dynamic hint}) =>
      RustLib.instance.api.protonEmailAddressClientGetAllPublicKeys(
          that: this, email: email, internalOnly: internalOnly, hint: hint);

  Future<List<ProtonAddress>> getProtonAddress({dynamic hint}) =>
      RustLib.instance.api
          .protonEmailAddressClientGetProtonAddress(that: this, hint: hint);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ProtonEmailAddressClient> newInstance(
          {required ProtonApiService service, dynamic hint}) =>
      RustLib.instance.api
          .protonEmailAddressClientNew(service: service, hint: hint);
}
