// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'keychain_kind.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FrbAddressInfo {
  /// Child index of this address
  final int index;

  /// Address
  final String address;

  /// Type of keychain
  final KeychainKind keychain;

  const FrbAddressInfo({
    required this.index,
    required this.address,
    required this.keychain,
  });

  @override
  int get hashCode => index.hashCode ^ address.hashCode ^ keychain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbAddressInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          address == other.address &&
          keychain == other.keychain;
}
