// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RecommendedFees {
  /// Fee rate in sat/vB to place the transaction in the first mempool block
  final int fastestFee;

  /// Fee rate in sat/vB to usually confirm within half hour and place the transaction in between the first and second mempool blocks
  final int halfHourFee;

  /// Fee rate in sat/vB to usually confirm within one hour and place the transaction in between the second and third mempool blocks
  final int hourFee;

  /// Either 2 times the minimum fees, or the low priority rate (whichever is lower)
  final int economyFee;

  /// Minimum fee rate in sat/vB for transaction to be accepted
  final int minimumFee;

  const RecommendedFees({
    required this.fastestFee,
    required this.halfHourFee,
    required this.hourFee,
    required this.economyFee,
    required this.minimumFee,
  });

  @override
  int get hashCode =>
      fastestFee.hashCode ^
      halfHourFee.hashCode ^
      hourFee.hashCode ^
      economyFee.hashCode ^
      minimumFee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendedFees &&
          runtimeType == other.runtimeType &&
          fastestFee == other.fastestFee &&
          halfHourFee == other.halfHourFee &&
          hourFee == other.hourFee &&
          economyFee == other.economyFee &&
          minimumFee == other.minimumFee;
}
