// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'confirmation_time.freezed.dart';

@freezed
sealed class ConfirmationTime with _$ConfirmationTime {
  const ConfirmationTime._();

  /// The transaction is confirmed
  const factory ConfirmationTime.confirmed({
    /// Confirmation height.
    required int height,

    /// Confirmation time in unix seconds.
    required BigInt time,
  }) = ConfirmationTime_Confirmed;

  /// The transaction is unconfirmed
  const factory ConfirmationTime.unconfirmed({
    /// The last-seen timestamp in unix seconds.
    required BigInt lastSeen,
  }) = ConfirmationTime_Unconfirmed;
}
