// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Pagination {
  final BigInt skip;
  final BigInt take;

  const Pagination({
    required this.skip,
    required this.take,
  });

  @override
  int get hashCode => skip.hashCode ^ take.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Pagination &&
          runtimeType == other.runtimeType &&
          skip == other.skip &&
          take == other.take;
}

enum SortOrder {
  asc,
  desc,
  ;
}

enum TransactionFilter {
  all,
  receive,
  send,
  ;
}
