// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ExchangeRateModel {
  final int? id;
  final String serverId;
  final String bitcoinUnit;
  final String fiatCurrency;
  final String sign;
  final String exchangeRateTime;
  final int exchangeRate;
  final int cents;

  const ExchangeRateModel({
    this.id,
    required this.serverId,
    required this.bitcoinUnit,
    required this.fiatCurrency,
    required this.sign,
    required this.exchangeRateTime,
    required this.exchangeRate,
    required this.cents,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      serverId.hashCode ^
      bitcoinUnit.hashCode ^
      fiatCurrency.hashCode ^
      sign.hashCode ^
      exchangeRateTime.hashCode ^
      exchangeRate.hashCode ^
      cents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExchangeRateModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          serverId == other.serverId &&
          bitcoinUnit == other.bitcoinUnit &&
          fiatCurrency == other.fiatCurrency &&
          sign == other.sign &&
          exchangeRateTime == other.exchangeRateTime &&
          exchangeRate == other.exchangeRate &&
          cents == other.cents;
}
