// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ProtonUserModel {
  final int id;
  final String userId;
  final String name;
  final BigInt usedSpace;
  final String currency;
  final int credit;
  final BigInt createTime;
  final BigInt maxSpace;
  final BigInt maxUpload;
  final int role;
  final int private;
  final int subscribed;
  final int services;
  final int delinquent;
  final String? organizationPrivateKey;
  final String? email;
  final String? displayName;

  const ProtonUserModel({
    required this.id,
    required this.userId,
    required this.name,
    required this.usedSpace,
    required this.currency,
    required this.credit,
    required this.createTime,
    required this.maxSpace,
    required this.maxUpload,
    required this.role,
    required this.private,
    required this.subscribed,
    required this.services,
    required this.delinquent,
    this.organizationPrivateKey,
    this.email,
    this.displayName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      name.hashCode ^
      usedSpace.hashCode ^
      currency.hashCode ^
      credit.hashCode ^
      createTime.hashCode ^
      maxSpace.hashCode ^
      maxUpload.hashCode ^
      role.hashCode ^
      private.hashCode ^
      subscribed.hashCode ^
      services.hashCode ^
      delinquent.hashCode ^
      organizationPrivateKey.hashCode ^
      email.hashCode ^
      displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtonUserModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          name == other.name &&
          usedSpace == other.usedSpace &&
          currency == other.currency &&
          credit == other.credit &&
          createTime == other.createTime &&
          maxSpace == other.maxSpace &&
          maxUpload == other.maxUpload &&
          role == other.role &&
          private == other.private &&
          subscribed == other.subscribed &&
          services == other.services &&
          delinquent == other.delinquent &&
          organizationPrivateKey == other.organizationPrivateKey &&
          email == other.email &&
          displayName == other.displayName;
}
