// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class WalletUserSettingsModel {
  final String userId;
  final String bitcoinUnit;
  final String fiatCurrency;
  final int hideEmptyUsedAddresses;
  final int showWalletRecovery;
  final double twoFactorAmountThreshold;
  final int receiveInviterNotification;
  final int receiveEmailIntegrationNotification;
  final int walletCreated;
  final int acceptTermsAndConditions;

  const WalletUserSettingsModel({
    required this.userId,
    required this.bitcoinUnit,
    required this.fiatCurrency,
    required this.hideEmptyUsedAddresses,
    required this.showWalletRecovery,
    required this.twoFactorAmountThreshold,
    required this.receiveInviterNotification,
    required this.receiveEmailIntegrationNotification,
    required this.walletCreated,
    required this.acceptTermsAndConditions,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      bitcoinUnit.hashCode ^
      fiatCurrency.hashCode ^
      hideEmptyUsedAddresses.hashCode ^
      showWalletRecovery.hashCode ^
      twoFactorAmountThreshold.hashCode ^
      receiveInviterNotification.hashCode ^
      receiveEmailIntegrationNotification.hashCode ^
      walletCreated.hashCode ^
      acceptTermsAndConditions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletUserSettingsModel &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          bitcoinUnit == other.bitcoinUnit &&
          fiatCurrency == other.fiatCurrency &&
          hideEmptyUsedAddresses == other.hideEmptyUsedAddresses &&
          showWalletRecovery == other.showWalletRecovery &&
          twoFactorAmountThreshold == other.twoFactorAmountThreshold &&
          receiveInviterNotification == other.receiveInviterNotification &&
          receiveEmailIntegrationNotification ==
              other.receiveEmailIntegrationNotification &&
          walletCreated == other.walletCreated &&
          acceptTermsAndConditions == other.acceptTermsAndConditions;
}
