// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../common/errors.dart';
import '../../frb_generated.dart';
import '../../proton_wallet/crypto/wallet_key.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FrbWalletKeyHelper {
  const FrbWalletKeyHelper();

  /// Decrypts the encrypted text using AES-GCM with 256-bit key.
  static String decrypt(
          {required String base64SecureKey, required String encryptText}) =>
      RustLib.instance.api
          .crateApiCryptoWalletKeyHelperFrbWalletKeyHelperDecrypt(
              base64SecureKey: base64SecureKey, encryptText: encryptText);

  /// Encrypts the plaintext using AES-GCM with 256-bit key.
  static String encrypt(
          {required String base64SecureKey, required String plaintext}) =>
      RustLib.instance.api
          .crateApiCryptoWalletKeyHelperFrbWalletKeyHelperEncrypt(
              base64SecureKey: base64SecureKey, plaintext: plaintext);

  /// Generates Wallet key
  static UnlockedWalletKey generateSecretKey() => RustLib.instance.api
      .crateApiCryptoWalletKeyHelperFrbWalletKeyHelperGenerateSecretKey();

  /// Generates Wallet key output base64
  static String generateSecretKeyAsBase64() => RustLib.instance.api
      .crateApiCryptoWalletKeyHelperFrbWalletKeyHelperGenerateSecretKeyAsBase64();

  static UnlockedWalletKey generateWalletKey() => RustLib.instance.api
      .crateApiCryptoWalletKeyHelperFrbWalletKeyHelperGenerateWalletKey();

  /// Cryptographically secure pseudo-random number generation (CSPRNG).
  static Uint8List getSecureRandom({required BigInt length}) => RustLib
      .instance.api
      .crateApiCryptoWalletKeyHelperFrbWalletKeyHelperGetSecureRandom(
          length: length);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbWalletKeyHelper && runtimeType == other.runtimeType;
}
