// Mocks generated by Mockito 5.4.4 from annotations
// in wallet/test/snapshot/scenes/signin_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i13;

import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:wallet/constants/env.dart' as _i12;
import 'package:wallet/managers/manager.factory.dart' as _i7;
import 'package:wallet/scenes/core/coordinator.dart' as _i4;
import 'package:wallet/scenes/core/view.dart' as _i5;
import 'package:wallet/scenes/core/view.navigatior.identifiers.dart' as _i11;
import 'package:wallet/scenes/core/viewmodel.dart' as _i3;
import 'package:wallet/scenes/signin/signin.coordinator.dart' as _i2;
import 'package:wallet/scenes/signin/signin.viewmodel.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSigninCoordinator_0 extends _i1.SmartFake
    implements _i2.SigninCoordinator {
  _FakeSigninCoordinator_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeViewBase_1<V extends _i3.ViewModel<_i4.Coordinator>>
    extends _i1.SmartFake implements _i5.ViewBase<V> {
  _FakeViewBase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeGlobalKey_2<T extends _i6.State<_i6.StatefulWidget>>
    extends _i1.SmartFake implements _i6.GlobalKey<T> {
  _FakeGlobalKey_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeManagerFactory_3 extends _i1.SmartFake
    implements _i7.ManagerFactory {
  _FakeManagerFactory_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SigninViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSigninViewModel extends _i1.Mock implements _i8.SigninViewModel {
  MockSigninViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#errorMessage),
        ),
      ) as String);

  @override
  set errorMessage(String? _errorMessage) => super.noSuchMethod(
        Invocation.setter(
          #errorMessage,
          _errorMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SigninCoordinator get coordinator => (super.noSuchMethod(
        Invocation.getter(#coordinator),
        returnValue: _FakeSigninCoordinator_0(
          this,
          Invocation.getter(#coordinator),
        ),
      ) as _i2.SigninCoordinator);

  @override
  set currentSize(_i5.ViewSize? _currentSize) => super.noSuchMethod(
        Invocation.setter(
          #currentSize,
          _currentSize,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Stream<_i3.ViewModel<_i4.Coordinator>> get datasourceChanged =>
      (super.noSuchMethod(
        Invocation.getter(#datasourceChanged),
        returnValue: _i10.Stream<_i3.ViewModel<_i4.Coordinator>>.empty(),
      ) as _i10.Stream<_i3.ViewModel<_i4.Coordinator>>);

  @override
  bool get isMobileSize => (super.noSuchMethod(
        Invocation.getter(#isMobileSize),
        returnValue: false,
      ) as bool);

  @override
  bool get keepAlive => (super.noSuchMethod(
        Invocation.getter(#keepAlive),
        returnValue: false,
      ) as bool);

  @override
  bool get mobile => (super.noSuchMethod(
        Invocation.getter(#mobile),
        returnValue: false,
      ) as bool);

  @override
  bool get desktop => (super.noSuchMethod(
        Invocation.getter(#desktop),
        returnValue: false,
      ) as bool);

  @override
  bool get screenSizeState => (super.noSuchMethod(
        Invocation.getter(#screenSizeState),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> signIn(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            username,
            password,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void sinkAddSafe() => super.noSuchMethod(
        Invocation.method(
          #sinkAddSafe,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> loadData() => (super.noSuchMethod(
        Invocation.method(
          #loadData,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> move(_i11.NavID? to) => (super.noSuchMethod(
        Invocation.method(
          #move,
          [to],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [SigninCoordinator].
///
/// See the documentation for Mockito's code generation for more information.
class MockSigninCoordinator extends _i1.Mock implements _i2.SigninCoordinator {
  MockSigninCoordinator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ViewBase<_i3.ViewModel<_i4.Coordinator>> get widget =>
      (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeViewBase_1<_i3.ViewModel<_i4.Coordinator>>(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i5.ViewBase<_i3.ViewModel<_i4.Coordinator>>);

  @override
  set widget(_i5.ViewBase<_i3.ViewModel<_i4.Coordinator>>? _widget) =>
      super.noSuchMethod(
        Invocation.setter(
          #widget,
          _widget,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.GlobalKey<_i6.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_2<_i6.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i6.GlobalKey<_i6.NavigatorState>);

  @override
  _i7.ManagerFactory get serviceManager => (super.noSuchMethod(
        Invocation.getter(#serviceManager),
        returnValue: _FakeManagerFactory_3(
          this,
          Invocation.getter(#serviceManager),
        ),
      ) as _i7.ManagerFactory);

  @override
  void end() => super.noSuchMethod(
        Invocation.method(
          #end,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showHome(_i12.ApiEnv? env) => super.noSuchMethod(
        Invocation.method(
          #showHome,
          [env],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ViewBase<_i3.ViewModel<_i4.Coordinator>> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _FakeViewBase_1<_i3.ViewModel<_i4.Coordinator>>(
          this,
          Invocation.method(
            #start,
            [],
          ),
        ),
      ) as _i5.ViewBase<_i3.ViewModel<_i4.Coordinator>>);

  @override
  List<_i6.Widget> starts() => (super.noSuchMethod(
        Invocation.method(
          #starts,
          [],
        ),
        returnValue: <_i6.Widget>[],
      ) as List<_i6.Widget>);

  @override
  void showInBottomSheet(
    _i6.Widget? view, {
    _i13.Color? backgroundColor,
    bool? fullScreen = false,
    bool? enableDrag = true,
    bool? isDismissible = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showInBottomSheet,
          [view],
          {
            #backgroundColor: backgroundColor,
            #fullScreen: fullScreen,
            #enableDrag: enableDrag,
            #isDismissible: isDismissible,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushReplacement(
    _i6.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushReplacement,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushReplacementRemoveAll(
    _i6.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushReplacementRemoveAll,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void push(
    _i6.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #push,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pop() => super.noSuchMethod(
        Invocation.method(
          #pop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushCustom(
    _i6.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushCustom,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushReplacementCustom(
    _i6.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushReplacementCustom,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showDialog1(_i6.Widget? view) => super.noSuchMethod(
        Invocation.method(
          #showDialog1,
          [view],
        ),
        returnValueForMissingStub: null,
      );
}
