// Mocks generated by Mockito 5.4.4 from annotations
// in wallet/test/snapshot/scenes/twofa.disable_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i12;

import 'package:flutter/cupertino.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:wallet/managers/manager.factory.dart' as _i6;
import 'package:wallet/scenes/core/coordinator.dart' as _i3;
import 'package:wallet/scenes/core/view.dart' as _i5;
import 'package:wallet/scenes/core/view.navigatior.identifiers.dart' as _i10;
import 'package:wallet/scenes/core/viewmodel.dart' as _i4;
import 'package:wallet/scenes/two.factor.auth.disable/two.factor.auth.disable.coordinator.dart'
    as _i11;
import 'package:wallet/scenes/two.factor.auth.disable/two.factor.auth.disable.viewmodel.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTextEditingController_0 extends _i1.SmartFake
    implements _i2.TextEditingController {
  _FakeTextEditingController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFocusNode_1 extends _i1.SmartFake implements _i2.FocusNode {
  _FakeFocusNode_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeCoordinator_2 extends _i1.SmartFake implements _i3.Coordinator {
  _FakeCoordinator_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeViewBase_3<V extends _i4.ViewModel<_i3.Coordinator>>
    extends _i1.SmartFake implements _i5.ViewBase<V> {
  _FakeViewBase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeGlobalKey_4<T extends _i2.State<_i2.StatefulWidget>>
    extends _i1.SmartFake implements _i2.GlobalKey<T> {
  _FakeGlobalKey_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeManagerFactory_5 extends _i1.SmartFake
    implements _i6.ManagerFactory {
  _FakeManagerFactory_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TwoFactorAuthDisableViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTwoFactorAuthDisableViewModel extends _i1.Mock
    implements _i7.TwoFactorAuthDisableViewModel {
  MockTwoFactorAuthDisableViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.TextEditingController> get digitControllers => (super.noSuchMethod(
        Invocation.getter(#digitControllers),
        returnValue: <_i2.TextEditingController>[],
      ) as List<_i2.TextEditingController>);

  @override
  set digitControllers(List<_i2.TextEditingController>? _digitControllers) =>
      super.noSuchMethod(
        Invocation.setter(
          #digitControllers,
          _digitControllers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.TextEditingController get passwordController => (super.noSuchMethod(
        Invocation.getter(#passwordController),
        returnValue: _FakeTextEditingController_0(
          this,
          Invocation.getter(#passwordController),
        ),
      ) as _i2.TextEditingController);

  @override
  set passwordController(_i2.TextEditingController? _passwordController) =>
      super.noSuchMethod(
        Invocation.setter(
          #passwordController,
          _passwordController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.FocusNode get passphraseFocusNode => (super.noSuchMethod(
        Invocation.getter(#passphraseFocusNode),
        returnValue: _FakeFocusNode_1(
          this,
          Invocation.getter(#passphraseFocusNode),
        ),
      ) as _i2.FocusNode);

  @override
  set passphraseFocusNode(_i2.FocusNode? _passphraseFocusNode) =>
      super.noSuchMethod(
        Invocation.setter(
          #passphraseFocusNode,
          _passphraseFocusNode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#error),
        ),
      ) as String);

  @override
  set error(String? _error) => super.noSuchMethod(
        Invocation.setter(
          #error,
          _error,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Coordinator get coordinator => (super.noSuchMethod(
        Invocation.getter(#coordinator),
        returnValue: _FakeCoordinator_2(
          this,
          Invocation.getter(#coordinator),
        ),
      ) as _i3.Coordinator);

  @override
  set currentSize(_i5.ViewSize? _currentSize) => super.noSuchMethod(
        Invocation.setter(
          #currentSize,
          _currentSize,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Stream<_i4.ViewModel<_i3.Coordinator>> get datasourceChanged =>
      (super.noSuchMethod(
        Invocation.getter(#datasourceChanged),
        returnValue: _i9.Stream<_i4.ViewModel<_i3.Coordinator>>.empty(),
      ) as _i9.Stream<_i4.ViewModel<_i3.Coordinator>>);

  @override
  bool get isMobileSize => (super.noSuchMethod(
        Invocation.getter(#isMobileSize),
        returnValue: false,
      ) as bool);

  @override
  bool get keepAlive => (super.noSuchMethod(
        Invocation.getter(#keepAlive),
        returnValue: false,
      ) as bool);

  @override
  bool get mobile => (super.noSuchMethod(
        Invocation.getter(#mobile),
        returnValue: false,
      ) as bool);

  @override
  bool get desktop => (super.noSuchMethod(
        Invocation.getter(#desktop),
        returnValue: false,
      ) as bool);

  @override
  bool get android => (super.noSuchMethod(
        Invocation.getter(#android),
        returnValue: false,
      ) as bool);

  @override
  bool get iOS => (super.noSuchMethod(
        Invocation.getter(#iOS),
        returnValue: false,
      ) as bool);

  @override
  bool get macOS => (super.noSuchMethod(
        Invocation.getter(#macOS),
        returnValue: false,
      ) as bool);

  @override
  bool get apple => (super.noSuchMethod(
        Invocation.getter(#apple),
        returnValue: false,
      ) as bool);

  @override
  bool get screenSizeState => (super.noSuchMethod(
        Invocation.getter(#screenSizeState),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<bool> disable2FA() => (super.noSuchMethod(
        Invocation.method(
          #disable2FA,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  void sinkAddSafe() => super.noSuchMethod(
        Invocation.method(
          #sinkAddSafe,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> loadData() => (super.noSuchMethod(
        Invocation.method(
          #loadData,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> move(_i10.NavID? to) => (super.noSuchMethod(
        Invocation.method(
          #move,
          [to],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [TwoFactorAuthDisableCoordinator].
///
/// See the documentation for Mockito's code generation for more information.
class MockTwoFactorAuthDisableCoordinator extends _i1.Mock
    implements _i11.TwoFactorAuthDisableCoordinator {
  MockTwoFactorAuthDisableCoordinator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ViewBase<_i4.ViewModel<_i3.Coordinator>> get widget =>
      (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeViewBase_3<_i4.ViewModel<_i3.Coordinator>>(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i5.ViewBase<_i4.ViewModel<_i3.Coordinator>>);

  @override
  set widget(_i5.ViewBase<_i4.ViewModel<_i3.Coordinator>>? _widget) =>
      super.noSuchMethod(
        Invocation.setter(
          #widget,
          _widget,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.GlobalKey<_i2.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_4<_i2.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i2.GlobalKey<_i2.NavigatorState>);

  @override
  _i6.ManagerFactory get serviceManager => (super.noSuchMethod(
        Invocation.getter(#serviceManager),
        returnValue: _FakeManagerFactory_5(
          this,
          Invocation.getter(#serviceManager),
        ),
      ) as _i6.ManagerFactory);

  @override
  void end() => super.noSuchMethod(
        Invocation.method(
          #end,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ViewBase<_i4.ViewModel<_i3.Coordinator>> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _FakeViewBase_3<_i4.ViewModel<_i3.Coordinator>>(
          this,
          Invocation.method(
            #start,
            [],
          ),
        ),
      ) as _i5.ViewBase<_i4.ViewModel<_i3.Coordinator>>);

  @override
  List<_i2.Widget> starts() => (super.noSuchMethod(
        Invocation.method(
          #starts,
          [],
        ),
        returnValue: <_i2.Widget>[],
      ) as List<_i2.Widget>);

  @override
  _i9.Future<bool> showInBottomSheet(
    _i2.Widget? view, {
    _i12.Color? backgroundColor,
    bool? fullScreen = false,
    bool? enableDrag = true,
    bool? isDismissible = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showInBottomSheet,
          [view],
          {
            #backgroundColor: backgroundColor,
            #fullScreen: fullScreen,
            #enableDrag: enableDrag,
            #isDismissible: isDismissible,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  void pushReplacement(
    _i2.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushReplacement,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushReplacementRemoveAll(
    _i2.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushReplacementRemoveAll,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void push(
    _i2.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #push,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pop() => super.noSuchMethod(
        Invocation.method(
          #pop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushCustom(
    _i2.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushCustom,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushReplacementCustom(
    _i2.Widget? view, {
    bool? fullscreenDialog = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushReplacementCustom,
          [view],
          {#fullscreenDialog: fullscreenDialog},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showDialog1(_i2.Widget? view) => super.noSuchMethod(
        Invocation.method(
          #showDialog1,
          [view],
        ),
        returnValueForMissingStub: null,
      );
}
