import 'package:wallet/rust/proton_api/user_settings.dart';

class FiatCurrencyInfo {
  String symbol;
  String sign;
  int cents;

  FiatCurrencyInfo(
      {required this.symbol, required this.sign, required this.cents});
}

class FiatCurrencyHelper {
  static String getText(FiatCurrency apiFiatCurrency) {
    String symbol = apiFiatCurrency.name.toUpperCase();
    String sign = "";
    if (fiatCurrency2Info.containsKey(apiFiatCurrency)) {
      sign = fiatCurrency2Info[apiFiatCurrency]!.sign;
    }
    return "$symbol ($sign)";
  }
}

// TODO:: those 3 constants should be moved to Rust and it could be auto gen
const List<FiatCurrency> fiatCurrencies = [
  FiatCurrency.usd,
  FiatCurrency.eur,
  FiatCurrency.chf,
  FiatCurrency.all,
  FiatCurrency.dzd,
  FiatCurrency.ars,
  FiatCurrency.amd,
  FiatCurrency.aud,
  FiatCurrency.azn,
  FiatCurrency.bhd,
  FiatCurrency.bdt,
  FiatCurrency.byn,
  FiatCurrency.bmd,
  FiatCurrency.bob,
  FiatCurrency.bam,
  FiatCurrency.brl,
  FiatCurrency.bgn,
  FiatCurrency.khr,
  FiatCurrency.cad,
  FiatCurrency.clp,
  FiatCurrency.cny,
  FiatCurrency.cop,
  FiatCurrency.crc,
  FiatCurrency.hrk,
  FiatCurrency.cup,
  FiatCurrency.czk,
  FiatCurrency.dkk,
  FiatCurrency.dop,
  FiatCurrency.egp,
  FiatCurrency.gel,
  FiatCurrency.ghs,
  FiatCurrency.gtq,
  FiatCurrency.hnl,
  FiatCurrency.hkd,
  FiatCurrency.huf,
  FiatCurrency.isk,
  FiatCurrency.inr,
  FiatCurrency.idr,
  FiatCurrency.irr,
  FiatCurrency.iqd,
  FiatCurrency.ils,
  FiatCurrency.jmd,
  FiatCurrency.jpy,
  FiatCurrency.jod,
  FiatCurrency.kzt,
  FiatCurrency.kes,
  FiatCurrency.kwd,
  FiatCurrency.kgs,
  FiatCurrency.lbp,
  FiatCurrency.mkd,
  FiatCurrency.myr,
  FiatCurrency.mur,
  FiatCurrency.mxn,
  FiatCurrency.mdl,
  FiatCurrency.mnt,
  FiatCurrency.mad,
  FiatCurrency.mmk,
  FiatCurrency.nad,
  FiatCurrency.npr,
  FiatCurrency.twd,
  FiatCurrency.nzd,
  FiatCurrency.nio,
  FiatCurrency.ngn,
  FiatCurrency.nok,
  FiatCurrency.omr,
  FiatCurrency.pkr,
  FiatCurrency.pab,
  FiatCurrency.pen,
  FiatCurrency.php,
  FiatCurrency.pln,
  FiatCurrency.gbp,
  FiatCurrency.qar,
  FiatCurrency.ron,
  FiatCurrency.rub,
  FiatCurrency.sar,
  FiatCurrency.rsd,
  FiatCurrency.sgd,
  FiatCurrency.zar,
  FiatCurrency.krw,
  FiatCurrency.ssp,
  FiatCurrency.ves,
  FiatCurrency.lkr,
  FiatCurrency.sek,
  FiatCurrency.thb,
  FiatCurrency.ttd,
  FiatCurrency.tnd,
  FiatCurrency.ugx,
  FiatCurrency.uah,
  FiatCurrency.aed,
  FiatCurrency.uyu,
  FiatCurrency.uzs,
  FiatCurrency.vnd,
];

final Map<FiatCurrency, FiatCurrencyInfo> fiatCurrency2Info = {
  FiatCurrency.all: FiatCurrencyInfo(symbol: 'all', sign: 'L', cents: 100),
  FiatCurrency.dzd: FiatCurrencyInfo(symbol: 'dzd', sign: 'د.ج', cents: 100),
  FiatCurrency.ars: FiatCurrencyInfo(symbol: 'ars', sign: '\$', cents: 100),
  FiatCurrency.amd: FiatCurrencyInfo(symbol: 'amd', sign: '֏', cents: 100),
  FiatCurrency.aud: FiatCurrencyInfo(symbol: 'aud', sign: '\$', cents: 100),
  FiatCurrency.azn: FiatCurrencyInfo(symbol: 'azn', sign: '₼', cents: 100),
  FiatCurrency.bhd: FiatCurrencyInfo(symbol: 'bhd', sign: '.د.ب', cents: 1000),
  FiatCurrency.bdt: FiatCurrencyInfo(symbol: 'bdt', sign: '৳', cents: 100),
  FiatCurrency.byn: FiatCurrencyInfo(symbol: 'byn', sign: 'Br', cents: 100),
  FiatCurrency.bmd: FiatCurrencyInfo(symbol: 'bmd', sign: '\$', cents: 100),
  FiatCurrency.bob: FiatCurrencyInfo(symbol: 'bob', sign: 'Bs.', cents: 100),
  FiatCurrency.bam: FiatCurrencyInfo(symbol: 'bam', sign: 'KM', cents: 100),
  FiatCurrency.brl: FiatCurrencyInfo(symbol: 'brl', sign: 'R\$', cents: 100),
  FiatCurrency.bgn: FiatCurrencyInfo(symbol: 'bgn', sign: 'лв', cents: 100),
  FiatCurrency.khr: FiatCurrencyInfo(symbol: 'khr', sign: '៛', cents: 100),
  FiatCurrency.cad: FiatCurrencyInfo(symbol: 'cad', sign: '\$', cents: 100),
  FiatCurrency.clp: FiatCurrencyInfo(symbol: 'clp', sign: '\$', cents: 1),
  FiatCurrency.cny: FiatCurrencyInfo(symbol: 'cny', sign: '¥', cents: 100),
  FiatCurrency.cop: FiatCurrencyInfo(symbol: 'cop', sign: '\$', cents: 100),
  FiatCurrency.crc: FiatCurrencyInfo(symbol: 'crc', sign: '₡', cents: 100),
  FiatCurrency.hrk: FiatCurrencyInfo(symbol: 'hrk', sign: 'kn', cents: 100),
  FiatCurrency.cup: FiatCurrencyInfo(symbol: 'cup', sign: '\$', cents: 100),
  FiatCurrency.czk: FiatCurrencyInfo(symbol: 'czk', sign: 'Kč', cents: 100),
  FiatCurrency.dkk: FiatCurrencyInfo(symbol: 'dkk', sign: 'kr', cents: 100),
  FiatCurrency.dop: FiatCurrencyInfo(symbol: 'dop', sign: '\$', cents: 100),
  FiatCurrency.egp: FiatCurrencyInfo(symbol: 'egp', sign: '£', cents: 100),
  FiatCurrency.eur: FiatCurrencyInfo(symbol: 'eur', sign: '€', cents: 100),
  FiatCurrency.gel: FiatCurrencyInfo(symbol: 'gel', sign: '₾', cents: 100),
  FiatCurrency.ghs: FiatCurrencyInfo(symbol: 'ghs', sign: '₵', cents: 100),
  FiatCurrency.gtq: FiatCurrencyInfo(symbol: 'gtq', sign: 'Q', cents: 100),
  FiatCurrency.hnl: FiatCurrencyInfo(symbol: 'hnl', sign: 'L', cents: 100),
  FiatCurrency.hkd: FiatCurrencyInfo(symbol: 'hkd', sign: '\$', cents: 100),
  FiatCurrency.huf: FiatCurrencyInfo(symbol: 'huf', sign: 'Ft', cents: 1),
  FiatCurrency.isk: FiatCurrencyInfo(symbol: 'isk', sign: 'kr', cents: 1),
  FiatCurrency.inr: FiatCurrencyInfo(symbol: 'inr', sign: '₹', cents: 100),
  FiatCurrency.idr: FiatCurrencyInfo(symbol: 'idr', sign: 'Rp', cents: 100),
  FiatCurrency.irr: FiatCurrencyInfo(symbol: 'irr', sign: '﷼', cents: 100),
  FiatCurrency.iqd: FiatCurrencyInfo(symbol: 'iqd', sign: 'ع.د', cents: 1000),
  FiatCurrency.ils: FiatCurrencyInfo(symbol: 'ils', sign: '₪', cents: 100),
  FiatCurrency.jmd: FiatCurrencyInfo(symbol: 'jmd', sign: '\$', cents: 100),
  FiatCurrency.jpy: FiatCurrencyInfo(symbol: 'jpy', sign: '¥', cents: 1),
  FiatCurrency.jod: FiatCurrencyInfo(symbol: 'jod', sign: 'د.ا', cents: 1000),
  FiatCurrency.kzt: FiatCurrencyInfo(symbol: 'kzt', sign: '₸', cents: 100),
  FiatCurrency.kes: FiatCurrencyInfo(symbol: 'kes', sign: 'Sh', cents: 100),
  FiatCurrency.kwd: FiatCurrencyInfo(symbol: 'kwd', sign: 'د.ك', cents: 1000),
  FiatCurrency.kgs: FiatCurrencyInfo(symbol: 'kgs', sign: 'с', cents: 100),
  FiatCurrency.lbp: FiatCurrencyInfo(symbol: 'lbp', sign: 'ل.ل', cents: 100),
  FiatCurrency.mkd: FiatCurrencyInfo(symbol: 'mkd', sign: 'ден', cents: 100),
  FiatCurrency.myr: FiatCurrencyInfo(symbol: 'myr', sign: 'RM', cents: 100),
  FiatCurrency.mur: FiatCurrencyInfo(symbol: 'mur', sign: '₨', cents: 100),
  FiatCurrency.mxn: FiatCurrencyInfo(symbol: 'mxn', sign: '\$', cents: 100),
  FiatCurrency.mdl: FiatCurrencyInfo(symbol: 'mdl', sign: 'L', cents: 100),
  FiatCurrency.mnt: FiatCurrencyInfo(symbol: 'mnt', sign: '₮', cents: 100),
  FiatCurrency.mad: FiatCurrencyInfo(symbol: 'mad', sign: 'د.م.', cents: 100),
  FiatCurrency.mmk: FiatCurrencyInfo(symbol: 'mmk', sign: 'Ks', cents: 100),
  FiatCurrency.nad: FiatCurrencyInfo(symbol: 'nad', sign: '\$', cents: 100),
  FiatCurrency.npr: FiatCurrencyInfo(symbol: 'npr', sign: '₨', cents: 100),
  FiatCurrency.twd: FiatCurrencyInfo(symbol: 'twd', sign: 'NT\$', cents: 1),
  FiatCurrency.nzd: FiatCurrencyInfo(symbol: 'nzd', sign: '\$', cents: 100),
  FiatCurrency.nio: FiatCurrencyInfo(symbol: 'nio', sign: 'C\$', cents: 100),
  FiatCurrency.ngn: FiatCurrencyInfo(symbol: 'ngn', sign: '₦', cents: 100),
  FiatCurrency.nok: FiatCurrencyInfo(symbol: 'nok', sign: 'kr', cents: 100),
  FiatCurrency.omr: FiatCurrencyInfo(symbol: 'omr', sign: 'ر.ع.', cents: 1000),
  FiatCurrency.pkr: FiatCurrencyInfo(symbol: 'pkr', sign: '₨', cents: 100),
  FiatCurrency.pab: FiatCurrencyInfo(symbol: 'pab', sign: 'B/.', cents: 100),
  FiatCurrency.pen: FiatCurrencyInfo(symbol: 'pen', sign: 'S/.', cents: 100),
  FiatCurrency.php: FiatCurrencyInfo(symbol: 'php', sign: '₱', cents: 100),
  FiatCurrency.pln: FiatCurrencyInfo(symbol: 'pln', sign: 'zł', cents: 100),
  FiatCurrency.gbp: FiatCurrencyInfo(symbol: 'gbp', sign: '£', cents: 100),
  FiatCurrency.qar: FiatCurrencyInfo(symbol: 'qar', sign: 'ر.ق', cents: 100),
  FiatCurrency.ron: FiatCurrencyInfo(symbol: 'ron', sign: 'lei', cents: 100),
  FiatCurrency.rub: FiatCurrencyInfo(symbol: 'rub', sign: '₽', cents: 100),
  FiatCurrency.sar: FiatCurrencyInfo(symbol: 'sar', sign: 'ر.س', cents: 100),
  FiatCurrency.rsd: FiatCurrencyInfo(symbol: 'rsd', sign: 'дин.', cents: 100),
  FiatCurrency.sgd: FiatCurrencyInfo(symbol: 'sgd', sign: 'S\$', cents: 100),
  FiatCurrency.zar: FiatCurrencyInfo(symbol: 'zar', sign: 'R', cents: 100),
  FiatCurrency.krw: FiatCurrencyInfo(symbol: 'krw', sign: '₩', cents: 1),
  FiatCurrency.ssp: FiatCurrencyInfo(symbol: 'ssp', sign: '£', cents: 100),
  FiatCurrency.ves: FiatCurrencyInfo(symbol: 'ves', sign: 'VES', cents: 100),
  FiatCurrency.lkr: FiatCurrencyInfo(symbol: 'lkr', sign: 'Rs', cents: 100),
  FiatCurrency.sek: FiatCurrencyInfo(symbol: 'sek', sign: 'kr', cents: 100),
  FiatCurrency.chf: FiatCurrencyInfo(symbol: 'chf', sign: 'Fr', cents: 100),
  FiatCurrency.thb: FiatCurrencyInfo(symbol: 'thb', sign: '฿', cents: 100),
  FiatCurrency.ttd: FiatCurrencyInfo(symbol: 'ttd', sign: 'TTD', cents: 100),
  FiatCurrency.tnd: FiatCurrencyInfo(symbol: 'tnd', sign: 'د.ت', cents: 1000),
  FiatCurrency.ugx: FiatCurrencyInfo(symbol: 'ugx', sign: 'UGX', cents: 1),
  FiatCurrency.uah: FiatCurrencyInfo(symbol: 'uah', sign: '₴', cents: 100),
  FiatCurrency.aed: FiatCurrencyInfo(symbol: 'aed', sign: 'د.إ', cents: 100),
  FiatCurrency.usd: FiatCurrencyInfo(symbol: 'usd', sign: '\$', cents: 100),
  FiatCurrency.uyu: FiatCurrencyInfo(symbol: 'uyu', sign: 'UYU', cents: 100),
  FiatCurrency.uzs: FiatCurrencyInfo(symbol: 'uzs', sign: 'UZS', cents: 100),
  FiatCurrency.vnd: FiatCurrencyInfo(symbol: 'vnd', sign: '₫', cents: 1),
};
