// Mocks generated by Mockito 5.4.4 from annotations
// in wallet/test/mocks/proton.exchange.rate.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:wallet/rust/proton_api/exchange_rate.dart' as _i2;
import 'package:wallet/rust/proton_api/user_settings.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProtonExchangeRate].
///
/// See the documentation for Mockito's code generation for more information.
class MockProtonExchangeRate extends _i1.Mock
    implements _i2.ProtonExchangeRate {
  MockProtonExchangeRate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i4.BitcoinUnit get bitcoinUnit => (super.noSuchMethod(
        Invocation.getter(#bitcoinUnit),
        returnValue: _i4.BitcoinUnit.btc,
      ) as _i4.BitcoinUnit);

  @override
  _i4.FiatCurrency get fiatCurrency => (super.noSuchMethod(
        Invocation.getter(#fiatCurrency),
        returnValue: _i4.FiatCurrency.all,
      ) as _i4.FiatCurrency);

  @override
  String get exchangeRateTime => (super.noSuchMethod(
        Invocation.getter(#exchangeRateTime),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#exchangeRateTime),
        ),
      ) as String);

  @override
  BigInt get exchangeRate => (super.noSuchMethod(
        Invocation.getter(#exchangeRate),
        returnValue: _i3.dummyValue<BigInt>(
          this,
          Invocation.getter(#exchangeRate),
        ),
      ) as BigInt);

  @override
  BigInt get cents => (super.noSuchMethod(
        Invocation.getter(#cents),
        returnValue: _i3.dummyValue<BigInt>(
          this,
          Invocation.getter(#cents),
        ),
      ) as BigInt);
}
