/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package gopenpgp */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "proton_crypto.go"

#include <stdlib.h>
#include <string.h>
struct BinaryResult {
    int length;
    char* data;
};

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* encryptWithKeyRing(char* userPublicKeysSepInComma, char* message);
extern char* getArmoredPublicKey(char* userPrivateKey);
extern char* encrypt(char* userPrivateKey, char* message);
extern char* getSignatureWithContext(char* userPrivateKey, char* passphrase, char* message, char* context);
extern int verifySignatureWithContext(char* userPublicKey, char* message, char* signature, char* context);
extern char* getBinarySignatureWithContext(char* userPrivateKey, char* passphrase, char* binaryMessage, int length, char* context);
extern int verifyBinarySignatureWithContext(char* userPublicKey, char* binaryMessage, int length, char* signature, char* context);
extern char* getSignature(char* userPrivateKey, char* passphrase, char* message);
extern int verifySignature(char* userPublicKey, char* message, char* signature);

/* Return type for verifyCleartextMessageArmored */
struct verifyCleartextMessageArmored_return {
	char* r0;
	int r1;
};
extern struct verifyCleartextMessageArmored_return verifyCleartextMessageArmored(char* userPublicKey, char* armoredSignature);
extern char* decrypt(char* userPrivateKey, char* passphrase, char* armor);
extern struct BinaryResult encryptBinary(char* userPrivateKey, char* binaryMessage, int length);
extern char* encryptBinaryArmor(char* userPrivateKey, char* binaryMessage, int length);
extern struct BinaryResult decryptBinary(char* userPrivateKey, char* passphrase, char* encryptedBinary, int length);
extern void enforce_binding();

#ifdef __cplusplus
}
#endif
