// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'user_settings.dart';
import 'wallet.dart';
import 'wallet_account.dart';
import 'wallet_settings.dart';

class ProtonEvent {
  final int code;
  final String eventId;
  final int more;
  final List<WalletEvent>? walletEvents;
  final List<WalletAccountEvent>? walletAccountEvents;
  final List<WalletKeyEvent>? walletKeyEvents;
  final List<WalletSettingsEvent>? walletSettingEvents;
  final ApiUserSettings? walletUserSettings;

  const ProtonEvent({
    required this.code,
    required this.eventId,
    required this.more,
    this.walletEvents,
    this.walletAccountEvents,
    this.walletKeyEvents,
    this.walletSettingEvents,
    this.walletUserSettings,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      eventId.hashCode ^
      more.hashCode ^
      walletEvents.hashCode ^
      walletAccountEvents.hashCode ^
      walletKeyEvents.hashCode ^
      walletSettingEvents.hashCode ^
      walletUserSettings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtonEvent &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          eventId == other.eventId &&
          more == other.more &&
          walletEvents == other.walletEvents &&
          walletAccountEvents == other.walletAccountEvents &&
          walletKeyEvents == other.walletKeyEvents &&
          walletSettingEvents == other.walletSettingEvents &&
          walletUserSettings == other.walletUserSettings;
}

class WalletAccountEvent {
  final String id;
  final int action;
  final WalletAccount? walletAccount;

  const WalletAccountEvent({
    required this.id,
    required this.action,
    this.walletAccount,
  });

  @override
  int get hashCode => id.hashCode ^ action.hashCode ^ walletAccount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletAccountEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          walletAccount == other.walletAccount;
}

class WalletEvent {
  final String id;
  final int action;
  final ProtonWallet? wallet;

  const WalletEvent({
    required this.id,
    required this.action,
    this.wallet,
  });

  @override
  int get hashCode => id.hashCode ^ action.hashCode ^ wallet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          wallet == other.wallet;
}

class WalletKeyEvent {
  final String id;
  final int action;
  final ProtonWalletKey? walletKey;

  const WalletKeyEvent({
    required this.id,
    required this.action,
    this.walletKey,
  });

  @override
  int get hashCode => id.hashCode ^ action.hashCode ^ walletKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletKeyEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          walletKey == other.walletKey;
}

class WalletSettingsEvent {
  final String id;
  final int action;
  final WalletSettings? walletSettings;

  const WalletSettingsEvent({
    required this.id,
    required this.action,
    this.walletSettings,
  });

  @override
  int get hashCode => id.hashCode ^ action.hashCode ^ walletSettings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletSettingsEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          walletSettings == other.walletSettings;
}
