// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ApiCountry {
  final String code;
  final String fiatCurrency;
  final String name;

  const ApiCountry({
    required this.code,
    required this.fiatCurrency,
    required this.name,
  });

  @override
  int get hashCode => code.hashCode ^ fiatCurrency.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiCountry &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          fiatCurrency == other.fiatCurrency &&
          name == other.name;
}

class ApiCountryFiatCurrency {
  final String name;
  final String symbol;

  const ApiCountryFiatCurrency({
    required this.name,
    required this.symbol,
  });

  @override
  int get hashCode => name.hashCode ^ symbol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiCountryFiatCurrency &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          symbol == other.symbol;
}

enum GatewayProvider {
  banxa,
  ramp,
  moonPay,
  unsupported,
  ;
}

enum PaymentMethod {
  applePay,
  bankTransfer,
  card,
  googlePay,
  instantPayment,
  unsupported,
  ;
}

class Quote {
  final String bitcoinAmount;
  final String fiatAmount;
  final String fiatCurrencySymbol;
  final String networkFee;
  final String paymentGatewayFee;
  final PaymentMethod paymentMethod;

  const Quote({
    required this.bitcoinAmount,
    required this.fiatAmount,
    required this.fiatCurrencySymbol,
    required this.networkFee,
    required this.paymentGatewayFee,
    required this.paymentMethod,
  });

  @override
  int get hashCode =>
      bitcoinAmount.hashCode ^
      fiatAmount.hashCode ^
      fiatCurrencySymbol.hashCode ^
      networkFee.hashCode ^
      paymentGatewayFee.hashCode ^
      paymentMethod.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Quote &&
          runtimeType == other.runtimeType &&
          bitcoinAmount == other.bitcoinAmount &&
          fiatAmount == other.fiatAmount &&
          fiatCurrencySymbol == other.fiatCurrencySymbol &&
          networkFee == other.networkFee &&
          paymentGatewayFee == other.paymentGatewayFee &&
          paymentMethod == other.paymentMethod;
}
