// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum ApiFiatCurrency {
  usd,
  eur,
  chf,
}

class ApiUserSettings {
  final CommonBitcoinUnit bitcoinUnit;
  final ApiFiatCurrency fiatCurrency;
  final int hideEmptyUsedAddresses;
  final int showWalletRecovery;
  final int? twoFactorAmountThreshold;

  const ApiUserSettings({
    required this.bitcoinUnit,
    required this.fiatCurrency,
    required this.hideEmptyUsedAddresses,
    required this.showWalletRecovery,
    this.twoFactorAmountThreshold,
  });

  @override
  int get hashCode =>
      bitcoinUnit.hashCode ^
      fiatCurrency.hashCode ^
      hideEmptyUsedAddresses.hashCode ^
      showWalletRecovery.hashCode ^
      twoFactorAmountThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiUserSettings &&
          runtimeType == other.runtimeType &&
          bitcoinUnit == other.bitcoinUnit &&
          fiatCurrency == other.fiatCurrency &&
          hideEmptyUsedAddresses == other.hideEmptyUsedAddresses &&
          showWalletRecovery == other.showWalletRecovery &&
          twoFactorAmountThreshold == other.twoFactorAmountThreshold;
}

enum CommonBitcoinUnit {
  /// 100,000,000 sats
  btc,

  /// 100,000 sats
  mbtc,

  /// 1 sat
  sats,
}
