// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ApiWalletSettings {
  final String walletId;
  final int hideAccounts;
  final String? invoiceDefaultDescription;
  final int invoiceExpirationTime;
  final int maxChannelOpeningFee;
  final bool? showWalletRecovery;

  const ApiWalletSettings({
    required this.walletId,
    required this.hideAccounts,
    this.invoiceDefaultDescription,
    required this.invoiceExpirationTime,
    required this.maxChannelOpeningFee,
    this.showWalletRecovery,
  });

  @override
  int get hashCode =>
      walletId.hashCode ^
      hideAccounts.hashCode ^
      invoiceDefaultDescription.hashCode ^
      invoiceExpirationTime.hashCode ^
      maxChannelOpeningFee.hashCode ^
      showWalletRecovery.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiWalletSettings &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          hideAccounts == other.hideAccounts &&
          invoiceDefaultDescription == other.invoiceDefaultDescription &&
          invoiceExpirationTime == other.invoiceExpirationTime &&
          maxChannelOpeningFee == other.maxChannelOpeningFee &&
          showWalletRecovery == other.showWalletRecovery;
}
