// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'user_settings.dart';

class ApiEmailAddress {
  final String id;
  final String email;

  const ApiEmailAddress({
    required this.id,
    required this.email,
  });

  @override
  int get hashCode => id.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiEmailAddress &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          email == other.email;
}

class ApiWalletAccount {
  final String id;
  final String walletId;
  final FiatCurrency fiatCurrency;
  final String derivationPath;
  final String label;
  final int priority;
  final int scriptType;
  final List<ApiEmailAddress> addresses;
  final int lastUsedIndex;

  const ApiWalletAccount({
    required this.id,
    required this.walletId,
    required this.fiatCurrency,
    required this.derivationPath,
    required this.label,
    required this.priority,
    required this.scriptType,
    required this.addresses,
    required this.lastUsedIndex,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      walletId.hashCode ^
      fiatCurrency.hashCode ^
      derivationPath.hashCode ^
      label.hashCode ^
      priority.hashCode ^
      scriptType.hashCode ^
      addresses.hashCode ^
      lastUsedIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiWalletAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          walletId == other.walletId &&
          fiatCurrency == other.fiatCurrency &&
          derivationPath == other.derivationPath &&
          label == other.label &&
          priority == other.priority &&
          scriptType == other.scriptType &&
          addresses == other.addresses &&
          lastUsedIndex == other.lastUsedIndex;
}

class CreateWalletAccountReq {
  final String label;
  final String derivationPath;
  final int scriptType;

  const CreateWalletAccountReq({
    required this.label,
    required this.derivationPath,
    required this.scriptType,
  });

  @override
  int get hashCode =>
      label.hashCode ^ derivationPath.hashCode ^ scriptType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateWalletAccountReq &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          derivationPath == other.derivationPath &&
          scriptType == other.scriptType;
}
