// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../proton_api/exchange_rate.dart';
import '../../proton_api/user_settings.dart';
import '../errors.dart';
import 'account.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbAccountStatementGenerator>>
abstract class FrbAccountStatementGenerator implements RustOpaqueInterface {
  void addAccount({required FrbAccount account, required String accountName});

  factory FrbAccountStatementGenerator({ProtonExchangeRate? exchangeRate}) =>
      RustLib.instance.api
          .crateApiBdkWalletAccountStatementGeneratorFrbAccountStatementGeneratorNew(
              exchangeRate: exchangeRate);

  Future<Uint8List> toCsv({required BigInt exportTime});

  Future<Uint8List> toPdf({required BigInt exportTime});
}
