// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../common/network.dart';
import '../../frb_generated.dart';
import '../errors.dart';
import 'balance.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'script_buf.dart';
import 'transaction_details.dart';

// These functions are ignored because they are not marked as `pub`: `clone_inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `cmp`, `eq`, `fmt`, `from`, `from`, `hash`, `partial_cmp`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbAddress>>
abstract class FrbAddress implements RustOpaqueInterface {
  static FrbAddress fromScript(
          {required FrbScriptBuf script, required Network network}) =>
      RustLib.instance.api.crateApiBdkWalletAddressFrbAddressFromScript(
          script: script, network: network);

  FrbScriptBuf intoScript();

  factory FrbAddress({required String address, required Network network}) =>
      RustLib.instance.api.crateApiBdkWalletAddressFrbAddressNew(
          address: address, network: network);

  String toString();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbAddressDetails>>
abstract class FrbAddressDetails implements RustOpaqueInterface {
  String get address;

  FrbBalance get balance;

  int get index;

  List<FrbTransactionDetails> get transactions;

  set address(String address);

  set balance(FrbBalance balance);

  set index(int index);

  set transactions(List<FrbTransactionDetails> transactions);
}
