// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbAmount>>
@sealed
class FrbAmount extends RustOpaque {
  FrbAmount.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  FrbAmount.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FrbAmount,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FrbAmount,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FrbAmountPtr,
  );

  double toBtc({dynamic hint}) =>
      RustLib.instance.api.frbAmountToBtc(that: this, hint: hint);

  /// Gets the number of satoshis in this [`Amount`].
  int toSat({dynamic hint}) =>
      RustLib.instance.api.frbAmountToSat(that: this, hint: hint);
}
