// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'amount.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbBalance>>
abstract class FrbBalance implements RustOpaqueInterface {
  static Future<FrbBalance> default_() =>
      RustLib.instance.api.crateApiBdkWalletBalanceFrbBalanceDefault();

  /// Get the whole balance visible to the wallet.
  FrbAmount total();

  /// Get sum of trusted_pending and confirmed coins.
  ///
  /// This is the balance you can spend right now that shouldn't get cancelled via another party
  /// double spending it.
  FrbAmount trustedSpendable();
}
