// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../common/errors.dart';
import '../../common/network.dart';
import '../../common/script_type.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clone_inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `cmp`, `eq`, `fmt`, `from`, `hash`, `partial_cmp`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbDerivationPath>>
abstract class FrbDerivationPath implements RustOpaqueInterface {
  static FrbDerivationPath fromParts(
          {required ScriptType scriptType,
          required Network network,
          required int accountIndex}) =>
      RustLib.instance.api
          .crateApiBdkWalletDerivationPathFrbDerivationPathFromParts(
              scriptType: scriptType,
              network: network,
              accountIndex: accountIndex);

  factory FrbDerivationPath({required String path}) => RustLib.instance.api
      .crateApiBdkWalletDerivationPathFrbDerivationPathNew(path: path);
}
