// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../common/script_type.dart';
import '../../frb_generated.dart';
import 'derivation_path.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DiscoveredAccount>>
abstract class DiscoveredAccount implements RustOpaqueInterface {
  FrbDerivationPath get derivationPath;

  int get index;

  factory DiscoveredAccount(
          {required ScriptType scriptType,
          required int index,
          required FrbDerivationPath derivationPath}) =>
      RustLib.instance.api
          .crateApiBdkWalletDiscoveredAccountDiscoveredAccountNew(
              scriptType: scriptType,
              index: index,
              derivationPath: derivationPath);

  ScriptType get scriptType;
}
