// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../common/network.dart';
import '../../frb_generated.dart';
import '../errors.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbPaymentLink>>
abstract class FrbPaymentLink implements RustOpaqueInterface {
  String toString();

  String toUri();

  static FrbPaymentLink tryParse(
          {required String str, required Network network}) =>
      RustLib.instance.api.crateApiBdkWalletPaymentLinkFrbPaymentLinkTryParse(
          str: str, network: network);
}
