// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbScriptBuf>>
@sealed
class FrbScriptBuf extends RustOpaque {
  FrbScriptBuf.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  FrbScriptBuf.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FrbScriptBuf,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FrbScriptBuf,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FrbScriptBufPtr,
  );

  factory FrbScriptBuf({required List<int> rawOutputScript, dynamic hint}) =>
      RustLib.instance.api
          .frbScriptBufNew(rawOutputScript: rawOutputScript, hint: hint);

  Uint8List toBytes({dynamic hint}) =>
      RustLib.instance.api.frbScriptBufToBytes(that: this, hint: hint);
}
