// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `build`, `clone`, `fmt`

class WalletMobileConnectorFactory {
  final String folderPath;

  const WalletMobileConnectorFactory.raw({
    required this.folderPath,
  });

  factory WalletMobileConnectorFactory({required String folderPath}) =>
      RustLib.instance.api
          .crateApiBdkWalletStorageWalletMobileConnectorFactoryNew(
              folderPath: folderPath);

  @override
  int get hashCode => folderPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletMobileConnectorFactory &&
          runtimeType == other.runtimeType &&
          folderPath == other.folderPath;
}
