// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../common/transaction_time.dart';
import '../../frb_generated.dart';
import 'derivation_path.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'transaction_details_txop.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbTransactionDetails>>
abstract class FrbTransactionDetails implements RustOpaqueInterface {
  FrbDerivationPath get accountDerivationPath;

  BigInt? get fees;

  BigInt get value;

  BigInt get valueWithFee;

  bool get isSend;

  List<FrbDetailledTxOutput> get outputs;

  TransactionTime get time;

  String get txid;

  BigInt get vbytesSize;
}
