// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../common/errors.dart';
import '../../frb_generated.dart';
import '../../srp/proofs.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SrpClient {
  const SrpClient.raw();

  static Future<String> computeKeyPassword(
          {required String password, required List<int> salt, dynamic hint}) =>
      RustLib.instance.api.srpClientComputeKeyPassword(
          password: password, salt: salt, hint: hint);

  static Future<SRPProofB64> generateProofs(
          {required String loginPassword,
          required int version,
          required String salt,
          required String modulus,
          required String serverEphemeral,
          dynamic hint}) =>
      RustLib.instance.api.srpClientGenerateProofs(
          loginPassword: loginPassword,
          version: version,
          salt: salt,
          modulus: modulus,
          serverEphemeral: serverEphemeral,
          hint: hint);

  static Future<SRPVerifierB64> generateVerifer(
          {required String password,
          String? saltOpt,
          required String serverModulus,
          dynamic hint}) =>
      RustLib.instance.api.srpClientGenerateVerifer(
          password: password,
          saltOpt: saltOpt,
          serverModulus: serverModulus,
          hint: hint);

  factory SrpClient({dynamic hint}) =>
      RustLib.instance.api.srpClientNew(hint: hint);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SrpClient && runtimeType == other.runtimeType;
}
